### ISSUE TITLE
`module load R/3.5.1` 실행시 에러

### ISSUE THREAD

**Issue by shanmdphd** [sp-edison/dev_manual#1]
Bulb에서 `module load R/3.5.1` 실행시 에러가 납니다.

```bash
$ module load R/3.5.1
R(4):ERROR:105: Unable to locate a modulefile for 'R/3.5.1'
$ module load R/3.5.0
R(4):ERROR:105: Unable to locate a modulefile for 'R/3.5.0'
```

`/SYSTEM/modulefiles/R` 경로에 3.3.2와 3.3.3에 대한 module만 생성된 것 같습니다.

최신 버전의 R에 대한 module을 사용할 수 있었으면 좋겠습니다.

**Comment by sp-edison** [comment]
안녕하세요. module를 사용해 R 3.5.0 3.5.1 활용할 수 있도록 시스템에 반영하였습니다.

**Comment by shanmdphd** [comment]
감사합니다.
